# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/constraints/soc_lite_top.xdc

# IP: /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/inst_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_ram || ORIG_REF_NAME==inst_ram} -quiet] -quiet

# IP: /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] -quiet
