# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.cache/wt [current_project]
set_property parent.project_path /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/func/obj/inst_ram.coe
add_files /home/ysyx/zzq/Code/AssemblerLangugae/test_jmp/inst_ram.coe
add_files /home/ysyx/zzq/Code/AssemblerLangugae/inst_ram.coe
add_files /home/ysyx/zzq/Code/AssemblerLangugae/test_Approch_Icache/inst_ram.coe
add_files /home/ysyx/zzq/Code/AssemblerLangugae/game/snake/snake_inst_ram.coe
add_files /home/ysyx/zzq/Code/AssemblerLangugae/test_rdcnt/test_rdcnt.coe
add_files /home/ysyx/zzq/Code/Verilog/vga_data/screenshot_video_data.coe
add_files /home/ysyx/zzq/Code/Python/adjust_picture_size/screenshot_video_data.coe
read_verilog {
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineAluOp.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineModuleBus.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineLoogLenWidth.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineCsrAddr.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineSignLocation.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineBJSign.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineWbSign.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineExcepSign.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineExSign.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineInstSign.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineIdSign.h
  /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineMemSign.h
  /home/ysyx/zzq/Code/Verilog/vga/vga.h
}
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineAluOp.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineModuleBus.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineLoogLenWidth.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineCsrAddr.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineSignLocation.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineBJSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineWbSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineExcepSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineExSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineInstSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineIdSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/LoogArch/paper_code2/DefineMemSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/zzq/Code/Verilog/vga/vga.h]
read_verilog -library xil_defaultlib {
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Arith_Logic_Unit.v
  {/home/ysyx/zzq/Code/Verilog/module_used _copy/Module_Clk_Div/Clk_Div_Ms_S.v}
  /home/ysyx/zzq/Code/LoogArch/paper_code2/CountReg.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Csr.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Data_Relevant.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Div.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/EX.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/EX_MEM.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/ExStage.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/ID.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/ID_EX.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/IF.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/IF_ID.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Icache.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/IcacheGroup.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/IfStage.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/IndetifyInstType.v
  {/home/ysyx/zzq/Code/Verilog/module_used _copy/Module_Led_Display/LED_display.v}
  {/home/ysyx/zzq/Code/Verilog/module_used _copy/Module_Led_Display/LED_show.v}
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Lanuch.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Loog.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/MEM.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/MEM_WB.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/MemStage.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/OpDecoder.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/PreIF.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Preif_IF.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Reg_File.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/Reg_File_Box.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/SignProduce.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/WB.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/WbStage.v
  /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/BRIDGE/bridge_1x2.v
  {/home/ysyx/zzq/Code/Verilog/module_used _copy/Module_Clk_Div/clk_div10.v}
  {/home/ysyx/zzq/Code/Verilog/module_used _copy/Module_Clk_Div/clk_div_ms.v}
  /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/CONFREG/confreg.v
  /home/ysyx/zzq/Code/Verilog/key/key_filter.v
  /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/myCPU/tools.v
  /home/ysyx/zzq/Code/Verilog/vga/vga_colorbat.v
  /home/ysyx/zzq/Code/Verilog/vga/vga_display.v
  /home/ysyx/zzq/Code/Verilog/vga/vga_drive.v
  /home/ysyx/zzq/Code/LoogArch/paper_code2/wallace_mul.v
  /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/soc_lite_top.v
}
read_ip -quiet /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/inst_ram.xci
set_property used_in_implementation false [get_files -all /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc]

read_ip -quiet /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc]

read_ip -quiet /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/video_ram/video_ram.xci
set_property used_in_implementation false [get_files -all /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/video_ram/video_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/constraints/soc_lite_top.xdc
set_property used_in_implementation false [get_files /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/constraints/soc_lite_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_lite_top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_lite_top_utilization_synth.rpt -pb soc_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
