# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/video_ram/video_ram.xci
# IP: The module: 'video_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/video_ram/video_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/video_ram/video_ram.xci
# IP: The module: 'video_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab06_exp13/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/video_ram/video_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
